27
harrisonfishco/Task pull request #41
Opened 2024-06-20 05:23 UTC by aozturk1

2024-06-20 15:12 UTC, harrisonfishco requested changes

2024-06-20 15:12 UTC, harrisonfishco commented on Task/Components/Pages/Settings.razor
> +                            System.Diagnostics.Debug.Print($"An error occurred: {ex.Message}");
TaskError.HandleError

2024-06-20 15:12 UTC, harrisonfishco commented on Task/Components/Pages/Settings.razor
> +    private void ValidateSettings()
Why doesn't this just return a bool?

2024-06-20 15:12 UTC, harrisonfishco commented on Task/Components/Pages/Settings.razor
> +    private void ValidateSettings()
Try catch

2024-06-20 15:12 UTC, harrisonfishco commented on Task/Components/Pages/Settings.razor
> +    private async Task Save()
Try catch

2024-06-20 15:12 UTC, harrisonfishco commented on Task/Components/Shared/TaskTextInput.razor
If this code is working great, if not, I would remove it.

2024-06-20 15:12 UTC, harrisonfishco commented on Task/Notifications/EmailNotification.cs
> +        public readonly string TASK_SMTP_SETTINGS_KEY = "TASK_SMTP_SETTINGS_KEY";
Move this to to top of file

2024-06-20 15:12 UTC, harrisonfishco commented on Task/Notifications/EmailNotification.cs
> +        public async void Send(TaskUser to, string subject, string message, NotificationContentType type = NotificationContentType.Info)
Try catch

2024-06-20 15:12 UTC, harrisonfishco commented on Task/Notifications/EmailNotification.cs
> +            var email = new MimeMessage();
No var

2024-06-20 15:12 UTC, harrisonfishco commented on Task/Notifications/EmailNotification.cs
> +                    TaskError.CreateUserError($"The file {FilePath} was not found.");
We should just create the default file if it doesn't exist

2024-06-20 15:12 UTC, harrisonfishco commented on Task/Notifications/EmailNotification.cs
> +            using (var client = new SmtpClient())
No var

2024-06-20 15:12 UTC, harrisonfishco commented on Task/Notifications/EmailNotification.cs
> +                    //TaskError.CreateUserError("Connected!");
Remove comment

2024-06-20 15:12 UTC, harrisonfishco commented on Task/Notifications/EmailNotification.cs
> +        public async Task<SmtpSettings> ReadSmtpSettings()
Try catch

2024-06-20 15:12 UTC, harrisonfishco commented on Task/Notifications/EmailNotification.cs
> +        public async Task<bool> WriteSmtpSettings(SmtpSettings settings)
Why do we return a bool if we can only return true?

2024-06-20 15:12 UTC, harrisonfishco commented on Task/Notifications/EmailNotification.cs
> +        private async void CreateDefaultFile(SmtpSettings? settings = null)
Try catch

2024-06-20 15:12 UTC, harrisonfishco commented on Task/Program.cs
> +            builder.Services.AddScoped<EmailNotification>();
Why are we adding EmailNotifcation. Shouldn't we pass email notification into the NotificationService which creates email notification?

2024-06-20 15:12 UTC, harrisonfishco commented on Task/Projects/Notification/TaskNotification.cs
Remove this

2024-06-22 19:49 UTC, aozturk1 commented on Task/Components/Layout/MainLayout.razor
> +@inject NotificationService Email;
DONE - this code was unused so I removed it

2024-06-22 19:53 UTC, aozturk1 commented on Task/Components/Pages/Settings.razor
> +@inject NotificationService Email;
DONE

2024-06-22 19:56 UTC, aozturk1 commented on Task/Components/Pages/Settings.razor
> +    private bool test = false;
DONE

2024-06-22 19:57 UTC, aozturk1 commented on Task/Components/Pages/Settings.razor
> +    private int testEmailCode = 0;
DONE

2024-06-22 20:01 UTC, aozturk1 commented on Task/Components/Pages/Settings.razor
> +                        catch (FileNotFoundException ex)
DONE

2024-06-22 20:01 UTC, aozturk1 commented on Task/Components/Pages/Settings.razor
> +                            System.Diagnostics.Debug.Print($"An error occurred: {ex.Message}");
DONE

2024-06-22 20:19 UTC, aozturk1 commented on Task/Components/Pages/Settings.razor
> +    private void ValidateSettings()
DONE

2024-06-22 20:20 UTC, aozturk1 commented on Task/Components/Pages/Settings.razor
> +    private async Task Save()
DONE

2024-06-22 20:28 UTC, aozturk1 commented on Task/Components/Shared/TaskTextInput.razor
Everything max length is removed but parsing and the rest works

2024-06-22 20:30 UTC, aozturk1 commented on Task/Notifications/EmailNotification.cs
> +        public readonly string TASK_SMTP_SETTINGS_KEY = "TASK_SMTP_SETTINGS_KEY";
DONE

2024-06-22 20:34 UTC, aozturk1 commented on Task/Notifications/EmailNotification.cs
> +        public async void Send(TaskUser to, string subject, string message, NotificationContentType type = NotificationContentType.Info)
DONE

2024-06-22 20:48 UTC, aozturk1 commented on Task/Notifications/EmailNotification.cs
> +                    TaskError.CreateUserError($"The file {FilePath} was not found.");
DONE

2024-06-22 20:48 UTC, aozturk1 commented on Task/Notifications/EmailNotification.cs
> +            var email = new MimeMessage();
DONE

2024-06-22 20:49 UTC, aozturk1 commented on Task/Notifications/EmailNotification.cs
> +            using (var client = new SmtpClient())
DONE

2024-06-22 20:50 UTC, aozturk1 commented on Task/Notifications/EmailNotification.cs
> +                    //TaskError.CreateUserError("Connected!");
DONE

2024-06-25 01:48 UTC, aozturk1 commented on Task/Notifications/EmailNotification.cs
> +        public async Task<SmtpSettings> ReadSmtpSettings()
DONE

2024-06-25 01:52 UTC, aozturk1 commented on Task/Notifications/EmailNotification.cs
> +        public async Task<bool> WriteSmtpSettings(SmtpSettings settings)
DONE

2024-06-25 01:54 UTC, aozturk1 commented on Task/Notifications/EmailNotification.cs
> +        private async void CreateDefaultFile(SmtpSettings? settings = null)
DONE

2024-06-25 01:58 UTC, aozturk1 commented on Task/Projects/Notification/TaskNotification.cs
DONE

2024-06-25 06:15 UTC, aozturk1 commented on Task/Program.cs
> +            builder.Services.AddScoped<EmailNotification>();
Because I am using many methods that are not defined in the INotification interface

2024-06-25 06:22 UTC, aozturk1 commented on Task/Components/Pages/Settings.razor
> +    private void ValidateSettings()
I am choosing a boolean value over a boolean method because the bool value is also used in the HTML and that way I don't have to call the method in order to show/hide the "Save" button

2024-06-26 05:15 UTC, harrisonfishco requested changes

2024-06-26 05:15 UTC, harrisonfishco commented on Task/Components/Pages/Settings.razor
> +    private void ValidateSettings()
Valid

2024-06-26 05:15 UTC, harrisonfishco commented on Task/Program.cs
> +            builder.Services.AddScoped<EmailNotification>();
This still shouldn't be a standalone service. The whole point of this is that we only need one service. If you want to use EmailNotification you can create an EmailNotification Object, you will still have the same functionality, you won't be using a service.

2024-06-26 05:15 UTC, harrisonfishco commented on Task/Components/Pages/Settings.razor
> +        <TaskTextInput Disabled="false" Label="From Mailbox Name" @bind-Value="SmtpSettings.FromMailboxName" @onfocus="DisableSave" @onclick="DisableSave"/>
We should replace `@onfocus` and `@onlick` with `@oninput`. This will disable the save button anytime a character is typed

2024-06-26 05:15 UTC, harrisonfishco commented on Task/Components/Pages/Settings.razor
> +        <TaskTextInput Disabled="false" Label="From Mailbox Name" @bind-Value="SmtpSettings.FromMailboxName" @onfocus="DisableSave" @onclick="DisableSave"/>
This also isn't working. Save button persists even after focus and confirm an edit on the field

2024-06-26 05:15 UTC, harrisonfishco commented on Task/Components/Pages/Settings.razor
> +        <br />
I would remove this break and give the test button a right margin

2024-06-26 05:15 UTC, harrisonfishco commented on Task/Components/Pages/Settings.razor
> +            <TaskButton OnClick="Save" Text="Save" Type="TaskButton.ButtonType.Default"/>
Make this TaskButton.ButtonType.Positive. We should indicate we are saving data

2024-06-26 05:15 UTC, harrisonfishco commented on Task/Components/Pages/Settings.razor
> +        <TaskTextInput Disabled="false" Label="From Email" @bind-Value="SmtpSettings.FromEmail" />
All the fields should force the user to retest the settings when edited

2024-06-26 05:15 UTC, harrisonfishco commented on Task/Components/Pages/Settings.razor
> +        <TaskTextInput Disabled="false" Label="Smtp Username(Email)" @bind-Value="SmtpSettings.SmtpUsername" />
We can remove "(Email)". This is only true for us.

2024-06-26 05:15 UTC, harrisonfishco commented on Task/Components/Pages/Settings.razor
> +@inject EmailNotification EmailNotif;
We should not be injecting EmailNotification since it shouldn't be a standalone service. Instead, you should create a local property that has a type of EmailNotification and use that. This way we don't register a global service that would only be used here

2024-06-27 15:15 UTC, harrisonfishco approved these changes
Everything looks really good, I want to do a functional test later when I get home. If everythings working, I'll merge. Great work.

2024-06-28 01:03 UTC, merged